### ISSUE TITLE
老哥，acc一直都是0啊。。

### ISSUE THREAD

**Issue by huangtianan** [yscoder-github/nl2sql-tianchi#1]

**Comment by yscoder-github** [comment]
你的执行命令是啥，是否已经加载fine-tune好的weights?  我看下你的日志

**Comment by huangtianan** [comment]
大佬，用这个python --mode train执行的，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"殷帅"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月30日(星期一) 下午3:49
收件人:&nbsp;"yscoder-github/nl2sql-tianchi"<nl2sql-tianchi@noreply.github.com&gt;;
抄送:&nbsp;"黄田安"<1003899428@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yscoder-github/nl2sql-tianchi] 老哥，acc一直都是0啊。。 (#1)




你的执行命令是啥，是否已经加载fine-tune好的weights?  我看下你的日志

**Comment by yscoder-github** [comment]
可以看下你的训练日志吗

**Comment by yscoder-github** [comment]
> 大佬，用这个python --mode train执行的，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"殷帅"<notifications@github.com&gt;; 发送时间:&nbsp;2019年9月30日(星期一) 下午3:49 收件人:&nbsp;"yscoder-github/nl2sql-tianchi"<nl2sql-tianchi@noreply.github.com&gt;; 抄送:&nbsp;"黄田安"<1003899428@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yscoder-github/nl2sql-tianchi] 老哥，acc一直都是0啊。。 (#1) 你的执行命令是啥，是否已经加载fine-tune好的weights? 我看下你的日志 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yscoder-github** [comment]
可以方便看下你的训练日志吗

**Comment by huangtianan** [comment]
已经加载了bert预训练模型，
![1569829913(1)](https://user-images.githubusercontent.com/19199077/65864491-89f22400-e3a4-11e9-9f55-8c1a28120fd9.jpg)

**Comment by yscoder-github** [comment]
我国庆看下哈，不知道为啥github的Issue我这里不显示了




------------------ 原始邮件 ------------------
发件人: "huangtianan"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午5:05
收件人: "yscoder-github/nl2sql-tianchi"<nl2sql-tianchi@noreply.github.com>;
抄送: "Yasser"<yscoder@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [yscoder-github/nl2sql-tianchi] 老哥，acc一直都是0啊。。 (#1)




已经加载了bert预训练模型，

**Comment by yscoder-github** [comment]
根据日志目测是模型并没有收敛，到Epoch29 loss还是很大,极有可能是学习率设置不合理




------------------ 原始邮件 ------------------
发件人: "huangtianan"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午5:05
收件人: "yscoder-github/nl2sql-tianchi"<nl2sql-tianchi@noreply.github.com>;
抄送: "Yasser"<yscoder@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [yscoder-github/nl2sql-tianchi] 老哥，acc一直都是0啊。。 (#1)




已经加载了bert预训练模型，

**Comment by yscoder-github** [comment]
你现在训练的咋样，我国庆训练了下，是没有问题的

**Comment by huangtianan** [comment]
老哥，现在模型是收敛的，准确率有问题
![微信图片_20191008145241](https://user-images.githubusercontent.com/19199077/66375879-04442900-e9e1-11e9-9e76-6fdcca4875be.png)
![微信图片_20191008145319](https://user-images.githubusercontent.com/19199077/66375883-06a68300-e9e1-11e9-823f-37e22486e43b.png)
![微信图片_20191008153225](https://user-images.githubusercontent.com/19199077/66375887-08704680-e9e1-11e9-99d9-73ccfe1c1d2d.png)

**Comment by yscoder-github** [comment]
https://github.com/yscoder-github/nl2sql-tianchi/blob/master/EXELOG.md 这个是我的训练日志,很好奇你这个是咋回事. 可以加微信看看你训练过程是不是有啥问题

**Comment by huangtianan** [comment]
老哥，太感谢了，这个是我微信号15521332355

**Comment by yscoder-github** [comment]
My wechat ID : 1959153545
